class_name GFServiceIds
extends RefCounted

const FRAMEWORK := &"framework"
const SERVICES := &"services"
const EVENTS := &"events"
const MESSAGES := &"messages"
const LOGGER := &"logger"
const MODULES := &"modules"
const RESOURCES := &"resources"
const SCENES := &"scenes"
const STORAGE := &"storage"
const SETTINGS := &"settings"
const POOLS := &"pools"
const STATE_MACHINES := &"state_machines"
const UI := &"ui"
const AUDIO := &"audio"
const INPUT := &"input"
const LOCALIZATION := &"localization"
const DOWNLOADS := &"downloads"
const CONTENT := &"content"
const TABLES := &"tables"
const CONNECTIVITY := &"connectivity"
